### ISSUE TITLE
Add API for the gateway itself

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-tradfri-client#77]
* [x] retrieving/subscribing to gateway info (#81)
* [x] reboot / reset (#82, WIP)
* [x] Documentation of the new methods (#83)
